### ISSUE TITLE
ConnectionResetError: [WinError 10054]

### ISSUE THREAD

**Issue by davesmeghead** [msp1974/visonic_proxy#28]
Hi Mark
Got this a couple of days ago but I'm not sure what caused it. I was experimenting and just noticed it in a log file
```
2024-11-08 06:51:47,501 INFO     Alarm client 7 disconnected
2024-11-08 06:51:47,501 INFO     Stopping keepalive timer for Alarm due to no connections
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Python312\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2024-11-08 06:51:47,501 INFO     Visonic 7 server has disconnected
2024-11-08 06:51:47,784 INFO     Received web connection request
2024-11-08 06:51:52,126 WARNING  ACK Timeout: Waiting for ACK from Alarm for msg id 2218
```

**Comment by msp1974** [comment]
Yes i have seen this too.  I think it when the Visonic server is having an issue or is down for maintenance.  Need to handle exception but i dont think it causes a proxy crash?
