### ISSUE TITLE
Integration crashes

### ISSUE THREAD

**Issue by msp1974** [msp1974/visonic_proxy#4]
Seen this in the HA logs a few times now.

```
2024-08-01 20:15:15.705 ERROR (MainThread) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed. (None)
Traceback (most recent call last):
File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1017, in _read_ready__data_received
self._protocol.data_received(data)
File "/config/custom_components/visonic/client.py", line 200, in data_received
super().vp_data_received(data)
File "/config/custom_components/visonic/pyvisonic.py", line 1973, in vp_data_received
self._handle_received_byte(databyte)
File "/config/custom_components/visonic/pyvisonic.py", line 2071, in _handle_received_byte
self._processReceivedMessage(ackneeded=self.pmCurrentPDU.ackneeded, debugp=self.pmCurrentPDU.debugprint, data=self.ReceiveData)
File "/config/custom_components/visonic/pyvisonic.py", line 2168, in _processReceivedMessage
self.packet_callback(data)
File "/config/custom_components/visonic/pyvisonic.py", line 3219, in _processReceivedPacket
self.handle_msgtypeA5(packet[2:-2])
File "/config/custom_components/visonic/pyvisonic.py", line 3970, in handle_msgtypeA5
self.ProcessX10StateUpdate(x10status=x10stat1 + (x10stat2 * 0x100))
File "/config/custom_components/visonic/pyvisonic.py", line 3858, in ProcessX10StateUpdate
self.SwitchList[i].pushChange()
TypeError: AlSwitchDeviceHelper.pushChange() missing 1 required positional argument: 's'
2024-08-01 20:15:15.707 ERROR (MainThread) [custom_components.visonic.pyvisonic] ERROR Connection Lost : disconnected because the Ethernet/USB connection was externally terminated. AlSwitchDeviceHelper.pushChange() missing 1 required positional argument: 's'
2024-08-01 20:15:15.707 ERROR (MainThread) [custom_components.visonic.pyvisonic] ERROR Connection Lost : disconnected due to exception AlSwitchDeviceHelper.pushChange() missing 1 required positional argument: 's'
2024-08-01 20:15:15.707 ERROR (MainThread) [custom_components.visonic.pyvisonic] No Exception handler to call, terminating Component......
```

**Comment by davesmeghead** [comment]
I believe that this is fixed in Integration release 0.9.9.5.
